# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: TERMINATORmdel101.MAUS
PackageVersion: 0.5.2
MinimumOSVersion: 10.0.22631.0
InstallerType: inno
Scope: machine
ElevationRequirement: elevatesSelf
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/TERMINATORmdel101/MAUS/releases/download/0.5.2/MAUS-0.5.2-installation.exe
  InstallerSha256: 6C9AB37DD25540D4A238EC22473F3392A796A1A7E1F44719A14666A00AB7B79A
  ProductCode: '{6F3D5F82-4668-473E-9693-0114543FC242}_is1'
  AppsAndFeaturesEntries:
  - DisplayName: MAUS
    Publisher: Projet MAUS (open source)
    ProductCode: '{6F3D5F82-4668-473E-9693-0114543FC242}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
